---
- name: install ftp and setings
  hosts: all
  become: true
  tasks:
    - name: Check linux family
      debug: var=ansible_os_family

    - name: install RedHat
      yum: name="{{ item }}" state=latest
      loop:
        - httpd
      when: ansible_os_family == "RedHat"

    - name: install Debian
      apt: name="{{ item }}" state=latest
      loop:
        - apache2
      when: ansible_os_family == "Debian"

    - name: copy
      copy:
        src: ./html/
        dest: /var/www/html

    - name: start httpd RedHat
      service: name=httpd state=restarted
      when: ansible_os_family == "RedHat"

    - name: start apache2 Debian
      service: name=apache2 state=restarted
      when: ansible_os_family == "Debian"
