---
- name: install ftp and setings
  hosts: all
  become: true
  tasks:
    - name: Check linux family
      debug: var=ansible_os_family

    - name: install RedHat
      yum: name="{{ item }}" state=present
      loop:
        - httpd
      when: ansible_os_family == "RedHat"

    - name: install Debian
      apt: name="{{ item }}" state=present
      loop:
        - apache2
      when: ansible_os_family == "Debian"

    - name: copy
      copy:
        src: ./html/
        dest: /var/www/html

    - name: Start Httpd in redhat
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
